In [148]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
from pandas_profiling import ProfileReport
import pickle

In [2]:
df=pd.read_csv("Admission_Prediction.csv")
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [3]:
# bulid a model and give me chancess of admission 

In [4]:
pf = ProfileReport(df)

In [5]:
pf.to_widgets()

In [6]:
# missing cell 40 so we have to handel it
# most of the data form the normaldistributed curve

In [7]:
df

Serial_No.  GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance_of_Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [8]:
# handel the missing value
df["GRE_Score"] = df["GRE_Score"].fillna(df["GRE_Score"].mean())

In [9]:
df["TOEFL_Score"] = df["TOEFL_Score"].fillna(df["TOEFL_Score"].mean())

In [10]:
df["University_Rating"] = df["University_Rating"].fillna(df["University_Rating"].mean())

In [11]:
df.describe()

Serial_No.   GRE_Score  TOEFL_Score  University_Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.103952     6.051338           1.128802    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  309.000000   103.000000           2.000000    2.500000   
50%    250.500000  316.558763   107.000000           3.000000    3.500000   
75%    375.250000  324.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance_of_Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [123]:
# now all value fill 
df.isnull().sum()

GRE_Score            0
TOEFL_Score          0
University_Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance_of_Admit      0
dtype: int64

In [13]:
df.drop(columns=["Serial_No."],inplace=True)

## Normalize technique 
standard scaler
dataset vary far so we not bring down dataset into lower scale so it will tough for my model to understand relation

#### Standard Scaler:- 
u = 0 (mean) and standard deviation =1

In [14]:
# now seperate the col-- feature(x1,x2x,x3....) and label(y)
y= df["Chance_of_Admit"]

In [15]:
x= df.drop(columns=["Chance_of_Admit"])

In [16]:
x

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [17]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance_of_Admit, Length: 500, dtype: float64

In [18]:
scaler = StandardScaler()

In [19]:
arr = scaler.fit_transform(x)

In [20]:
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [21]:
df1= pd.DataFrame(arr)

In [30]:
df1

0         1         2         3         4         5         6
0    1.842741e+00  1.788542  0.778906  1.137360  1.098944  1.776806  0.886405
1    6.708143e-01 -0.031058  0.778906  0.632315  1.098944  0.485859  0.886405
2    5.124333e-15 -0.527313 -0.107877 -0.377773  0.017306 -0.954043  0.886405
3    4.905178e-01  0.465197 -0.107877  0.127271 -1.064332  0.154847  0.886405
4   -2.306679e-01 -0.692731 -0.994659 -1.387862 -0.523513 -0.606480 -1.128152
..            ...       ...       ...       ...       ...       ...       ...
495  1.392000e+00  0.134360  1.665688  1.137360  0.558125  0.734118  0.886405
496  1.842741e+00  1.623124  1.665688  1.642404  1.639763  2.140919  0.886405
497  1.211704e+00  2.119379  1.665688  1.137360  1.639763  1.627851  0.886405
498 -4.109644e-01 -0.692731  0.778906  0.632315  1.639763 -0.242367 -1.128152
499  9.412590e-01  0.961451  0.778906  1.137360  1.098944  0.767220 -1.128152

[500 rows x 7 columns]

In [35]:
# now we see mean = 0 for every dataset --- standard deviation
df

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance_of_Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [38]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   4.350520e-15  9.419132e-16  5.608847e-16  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.394225e+00 -2.512331e+00 -1.881441e+00 -2.397950e+00 -2.686789e+00   
25%   -6.814090e-01 -6.927310e-01 -9.946589e-01 -8.828175e-01 -5.235128e-01   
50%    5.124333e-15 -3.105811e-02 -1.078766e-01  1.272712e-01  1.730621e-02   
75%    6.708143e-01  7.960330e-01  7.789057e-01  6.323155e-01  5.581253e-01   
max    2.113186e+00  2.119379e+00  1.665688e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

## Multicollinearity
1) Pearson plot
2) VIF 

vif=(1/1-R^2)
**vif>10 highly collinearity

In [39]:
# VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [41]:
variance_inflation_factor()   # it take x value and index of it

TypeError: variance_inflation_factor() missing 2 required positional arguments: 'exog' and 'exog_idx'

In [42]:
arr.shape

(500, 7)

In [44]:
# in case there shape{row=0,col=1}
arr.shape[1]

7

In [47]:
# now create new data frame to store the variance_inflation
vif_df = pd.DataFrame()

In [48]:
vif_df["vif"]=[variance_inflation_factor(arr,i) for i in range (arr.shape[1])]
    

In [46]:
# this are variance inflation factor for the each of the col 
# vif <10 so there is less collinearity
# so we suppose that drop any col and call the demonstrated reduction technique over here "pca " or "tsne" in particular place

In [49]:
vif_df

vif
0  4.153268
1  3.792866
2  2.508768
3  2.775750
4  2.037308
5  4.651670
6  1.459311

In [50]:
# now add the feature col in it
vif_df["feature"] = x.columns

In [51]:
vif_df

vif            feature
0  4.153268          GRE_Score
1  3.792866        TOEFL_Score
2  2.508768  University_Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

## Train-Test
spit data into training and testing

In [52]:
train_test_split(arr,y,test_size= 0.25)   # for testing purpose =25% and remaning 75% for trainning purpose

[array([[ 8.51110730e-01,  7.96032952e-01,  7.78905651e-01, ...,
          1.73062093e-02,  8.99624440e-01,  8.86405260e-01],
        [-5.01112585e-01, -3.61894539e-01, -1.07876604e-01, ...,
         -5.23512832e-01, -2.09265793e-01,  8.86405260e-01],
        [-2.30667922e-01,  0.00000000e+00,  7.78905651e-01, ...,
          5.58125251e-01,  3.20353423e-01,  8.86405260e-01],
        ...,
        [-1.49274302e+00, -1.18898560e+00,  3.93810431e-16, ...,
          1.73062093e-02, -5.23727202e-01, -1.12815215e+00],
        [-5.91260806e-01, -8.58149178e-01, -1.07876604e-01, ...,
          5.58125251e-01, -9.20941613e-01,  8.86405260e-01],
        [ 5.80666067e-01,  4.65196526e-01,  1.66568791e+00, ...,
          1.63976333e+00,  6.67916033e-01,  8.86405260e-01]]),
 array([[-5.01112585e-01, -3.10581135e-02,  7.78905651e-01,
          1.13735981e+00,  1.09894429e+00,  7.01017234e-01,
          8.86405260e-01],
        [ 5.80666067e-01,  9.61451165e-01, -1.07876604e-01,
          6.32315491e-

In [53]:
x_train,x_test,y_train,y_test = train_test_split(arr,y,test_size= 0.25) 

In [63]:
x_train   
#it split a data in random function -- change continues
# in numpy we us  seed function 
# in this case we use "random_state"

array([[ 1.30185183,  1.4577058 ,  0.77890565, ...,  1.09894429,
         1.42924366,  0.88640526],
       [-0.86170547, -0.85814918, -0.1078766 , ..., -0.52351283,
        -0.5071766 , -1.12815215],
       [ 0.12992496, -0.19647633, -0.99465886, ...,  0.55812525,
        -1.08644762,  0.88640526],
       ...,
       [-1.8533359 , -1.35440382, -0.99465886, ..., -1.06433187,
        -0.90439101, -1.12815215],
       [-1.13215013, -0.03105811, -0.1078766 , ..., -0.52351283,
        -1.18575122, -1.12815215],
       [-1.04200191, -0.69273097, -0.99465886, ...,  0.01730621,
        -0.73888501, -1.12815215]])

In [65]:
x_train,x_test,y_train,y_test = train_test_split(arr,y,test_size= 0.25,random_state = 345)

In [67]:
x_train  # now it not changes again and again

array([[-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [-1.67303946e+00, -1.02356739e+00,  7.78905651e-01, ...,
         1.09894429e+00, -1.46711143e+00,  8.86405260e-01],
       [-4.10964364e-01,  1.34360100e-01, -1.07876604e-01, ...,
        -5.23512832e-01, -7.68609886e-02, -1.12815215e+00],
       ...,
       [ 4.90517846e-01,  1.29228759e+00,  1.66568791e+00, ...,
         1.09894429e+00,  1.29683885e+00,  8.86405260e-01],
       [-1.67303946e+00, -1.68524024e+00,  3.93810431e-16, ...,
        -5.23512832e-01, -2.26154025e+00, -1.12815215e+00],
       [ 1.75259294e+00,  1.95396044e+00,  1.66568791e+00, ...,
         1.73062093e-02,  2.02506527e+00,  8.86405260e-01]])

## Linear Regression

In [68]:
lr = LinearRegression()

In [69]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [74]:
# create a file to dump this model
pickle.dump(lr,open("admission_lr_model.pickel","wb"))

In [75]:
df

GRE_Score  TOEFL_Score  University_Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance_of_Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [76]:
lr.predict([[315.0000,104.0,3.0,3.0,3.5,8.00,1]])
# chance of admit 0 to 1

array([9.08716858])

In [78]:
# in case we change the complete range of the dataset 
# here data set divided into 2 part traing and testing

# here we scale the data becoz we chage in the scaler data

In [87]:
test1=scaler.transform([[315.0000,104.0,3.0,3.0,3.5,8.00,1]])
# now it give scaler data

In [88]:
test1

array([[-0.1405197 , -0.52731275, -0.1078766 , -0.37777315,  0.01730621,
        -0.95404281,  0.88640526]])

In [80]:
lr.predict([[-0.1405197 , -0.52731275, -0.1078766 , -0.37777315,  0.01730621,
        -0.95404281,  0.88640526]])

array([0.65096324])

In [81]:
# now it give me original result

### pickel file opening

In [84]:
model= pickle.load(open("admission_lr_model.pickel","rb"))

In [89]:
model.predict(test1)

array([0.65096324])

In [91]:
lr.score(x_test,y_test)

0.7476466381844958

In [92]:
x_test

array([[-3.20816143e-01,  2.99778313e-01, -1.07876604e-01,
         6.32315491e-01,  1.73062093e-02,  7.01017234e-01,
        -1.12815215e+00],
       [-3.20816143e-01, -8.58149178e-01, -1.07876604e-01,
        -1.38786180e+00, -5.23512832e-01, -5.07176601e-01,
        -1.12815215e+00],
       [ 6.70814288e-01,  4.65196526e-01, -1.07876604e-01,
         1.27271169e-01, -5.23512832e-01,  1.06513044e+00,
         8.86405260e-01],
       [ 2.02303760e+00,  1.45770580e+00,  7.78905651e-01,
         6.32315491e-01,  1.73062093e-02,  2.02506527e+00,
         8.86405260e-01],
       [ 1.29924962e-01, -1.96476326e-01, -1.07876604e-01,
        -1.38786180e+00, -5.23512832e-01,  1.21746217e-01,
        -1.12815215e+00],
       [-4.10964364e-01, -3.61894539e-01, -9.94658860e-01,
        -1.38786180e+00, -1.06433187e+00, -2.09265793e-01,
        -1.12815215e+00],
       [ 1.29924962e-01,  2.99778313e-01, -1.07876604e-01,
         1.27271169e-01,  5.58125251e-01,  1.06513044e+00,
         8.8640526

In [93]:
y_test

289    0.79
167    0.64
371    0.89
148    0.96
391    0.71
       ... 
106    0.87
9      0.45
323    0.62
417    0.52
238    0.70
Name: Chance_of_Admit, Length: 125, dtype: float64

 in case 25% data is giving to testing dataset

## R^2 
calculate adj r^2

In [108]:
# Function for ----> adj r^2
def adj_r2(x,y):
    r2 = lr2.score(x,y)    # change lr ,  lr2 were we train model
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [98]:
adj_r2(x_test,y_test)

0.7325485738023716

In [99]:
# now change the randomness (100) for changing the accuracy
x_train,x_test,y_train,y_test = train_test_split(arr,y,test_size= 0.25,random_state = 100)

In [101]:
lr2 = LinearRegression()

In [102]:
lr2.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [103]:
lr2.score(x_test,y_test)

0.8262844735686963

In [104]:
# now as we see my score is improve

In [109]:
adj_r2(x_test,y_test)

0.8158912369446012

In [110]:
lr2.coef_

array([0.015458  , 0.01908417, 0.00381077, 0.00315846, 0.01678637,
       0.07622763, 0.01400522])

In [112]:
lr2.intercept_

0.7181156002659718

## CV -- cross validation-> lasso, ridge, logistic

### LassoCV

In [128]:
lassocv = LassoCV(cv= 10, max_iter=200000, normalize=True)  # iter -- max repetation
lassocv.fit(x_train,y_train)

LassoCV(alphas=None, copy_X=True, cv=10, eps=0.001, fit_intercept=True,
        max_iter=200000, n_alphas=100, n_jobs=None, normalize=True,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [125]:
lassocv.alpha_

9.742054000449748e-06

In [126]:
lasso = Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=9.742054000449748e-06, copy_X=True, fit_intercept=True,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [127]:
 lasso.score(x_test,y_test)

0.8262977741326505

 CV :-- it is technique to find out a best possible parameter by doing a random experiment
 
let:-  cv=5 [it divide my entire dataset 5 set]
in case first 4 set are -- training 
last set is for testing purpose
every time keep data rotating again and again then out of that find out best possible parameter

CV- best parameter finding / Cross validation
cv -> divide all chunk into dataset then it allot all the set (n-1) to "training" and nth or last one is for "testing" 

In [129]:
lassocv = LassoCV(cv= 5, max_iter=200000, normalize=True)  # iter -- max repetation
lassocv.fit(x_train,y_train)

LassoCV(alphas=None, copy_X=True, cv=5, eps=0.001, fit_intercept=True,
        max_iter=200000, n_alphas=100, n_jobs=None, normalize=True,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [130]:
lassocv.alpha_

2.7745719225519405e-05

In [133]:
lasso1 = Lasso(alpha=lassocv.alpha_)
lasso1.fit(x_train,y_train)

Lasso(alpha=2.7745719225519405e-05, copy_X=True, fit_intercept=True,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [134]:
 lasso1.score(x_test,y_test)

0.8263217068233789

## Ridge Regression

In [151]:
ridgecv = RidgeCV(alphas=(0.1,1.0,10.0),cv=10,normalize=True)
ridgecv.fit(x_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10, fit_intercept=True,
        gcv_mode=None, normalize=True, scoring=None, store_cv_values=False)

In [152]:
ridgecv.alpha_

0.1

Always try to give "wider range" of "alpha" 

this is hyper parameter
we try to select best possible alpha
so we use----> ["numpy.random.uniform"] ( rand-> uniform)

In [166]:
ridgecv2= RidgeCV(alphas = np.random.uniform(0,10,50),cv=10, normalize = True)
ridgecv2.fit(x_train ,y_train)

RidgeCV(alphas=array([4.62568761e+00, 8.39072331e+00, 5.01084893e+00, 8.45727323e-01,
       7.49405966e+00, 7.00203480e+00, 1.84014972e+00, 5.44930305e+00,
       9.30075712e+00, 5.02604723e+00, 5.38274690e+00, 5.13239533e+00,
       6.66365367e+00, 1.67581420e+00, 5.77967750e+00, 3.53645179e+00,
       6.09638930e+00, 2.68560969e+00, 7.70330887e+00, 4.37969084e+00,
       7.69201268e+00, 5.10518679e+0...
       2.56577481e+00, 6.84160663e+00, 9.21870218e+00, 2.77572293e+00,
       9.72017494e+00, 7.25568424e-01, 4.20289665e+00, 5.22033466e+00,
       7.30670109e+00, 5.21248798e-01, 9.90326726e+00, 5.80713722e+00,
       1.62544456e+00, 9.59512269e+00, 3.35833126e+00, 1.00018495e+00,
       4.58022003e+00, 7.36173592e-03]),
        cv=10, fit_intercept=True, gcv_mode=None, normalize=True, scoring=None,
        store_cv_values=False)

In [167]:
ridgecv2.alpha_

0.0073617359242539315

In [161]:
np.random.uniform(0,10,50)

array([9.36051401, 6.05667249, 6.1164797 , 5.41996624, 0.79315253,
       2.69779119, 6.12381183, 9.08866107, 6.82540341, 7.55091811,
       5.5784663 , 5.64358502, 2.8905204 , 6.88348029, 6.29804113,
       7.42802961, 5.14470066, 5.88399115, 0.56045869, 1.70881507,
       5.60957308, 5.20983875, 3.89625096, 6.75002079, 5.26536808,
       8.47561612, 4.41903441, 2.17090547, 9.74405901, 7.09508228,
       0.66732591, 3.41737655, 9.24911245, 8.31007083, 4.37901907,
       4.57178811, 4.4020981 , 2.96111569, 6.62542135, 6.07809679,
       6.95203547, 9.56258841, 1.33547009, 0.84545212, 8.73094808,
       9.32468341, 1.2821428 , 3.51539647, 7.87837826, 5.30261607])

In [170]:
ridgelr = Ridge(alpha = ridgecv2.alpha_)
ridgelr.fit(x_train , y_train)

Ridge(alpha=0.0073617359242539315, copy_X=True, fit_intercept=True,
      max_iter=None, normalize=False, random_state=None, solver='auto',
      tol=0.001)

In [171]:
ridgelr.score(x_test , y_test)

0.8262869853653665

## ElasticNetCV

In [173]:
elastic = ElasticNetCV(alphas= None , cv=10)
elastic.fit(x_train,y_train)

ElasticNetCV(alphas=None, copy_X=True, cv=10, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [174]:
elastic.alpha_

0.00032049828688228085

In [175]:
elastic.l1_ratio    

0.5

In [177]:
elastic_lr = ElasticNet(alpha= elastic.alpha_, l1_ratio=elastic.l1_ratio)

In [178]:
elastic_lr.fit(x_train ,y_train)

ElasticNet(alpha=0.00032049828688228085, copy_X=True, fit_intercept=True,
           l1_ratio=0.5, max_iter=1000, normalize=False, positive=False,
           precompute=False, random_state=None, selection='cyclic', tol=0.0001,
           warm_start=False)

In [179]:
elastic_lr.score(x_test,y_test)

0.8265118379982932